  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FUSION"."CUSTOM_CONTENT_ITEM" ("CONTENT_ITEM_ID", "BUSINESS_GROUP_ID", "CONTENT_ITEM_CODE", "CONTENT_KEYFLEX_ID", "CONTENT_SUPPLIER_CODE", "CONTENT_TYPE_ID", "CONTENT_VALUE_SET_ID", "COUNTRY_ID", "CREATED_BY", "CREATION_DATE", "DATE_FROM", "DATE_TO", "ITEM_DATE_1", "ITEM_DATE_10", "ITEM_DATE_2", "ITEM_DATE_3", "ITEM_DATE_4", "ITEM_DATE_5", "ITEM_DATE_6", "ITEM_DATE_7", "ITEM_DATE_8", "ITEM_DATE_9", "ITEM_DESCRIPTION", "ITEM_DESCRLONG", "ITEM_NUMBER_1", "ITEM_NUMBER_10", "ITEM_NUMBER_2", "ITEM_NUMBER_3", "ITEM_NUMBER_4", "ITEM_NUMBER_5", "ITEM_NUMBER_6", "ITEM_NUMBER_7", "ITEM_NUMBER_8", "ITEM_NUMBER_9", "ITEM_TEXT_1", "ITEM_TEXT_10", "ITEM_TEXT_11", "ITEM_TEXT_12", "ITEM_TEXT_13", "ITEM_TEXT_14", "ITEM_TEXT_15", "ITEM_TEXT_16", "ITEM_TEXT_17", "ITEM_TEXT_18", "ITEM_TEXT_19", "ITEM_TEXT_2", "ITEM_TEXT_20", "ITEM_TEXT_21", "ITEM_TEXT_22", "ITEM_TEXT_23", "ITEM_TEXT_24", "ITEM_TEXT_25", "ITEM_TEXT_26", "ITEM_TEXT_27", "ITEM_TEXT_28", "ITEM_TEXT_29", "ITEM_TEXT_3", "ITEM_TEXT_30", "ITEM_TEXT_4", "ITEM_TEXT_5", "ITEM_TEXT_6", "ITEM_TEXT_7", "ITEM_TEXT_8", "ITEM_TEXT_9", "ITEM_TEXT_TL_1", "ITEM_TEXT_TL_10", "ITEM_TEXT_TL_11", "ITEM_TEXT_TL_12", "ITEM_TEXT_TL_13", "ITEM_TEXT_TL_14", "ITEM_TEXT_TL_15", "ITEM_TEXT_TL_2", "ITEM_TEXT_TL_3", "ITEM_TEXT_TL_4", "ITEM_TEXT_TL_5", "ITEM_TEXT_TL_6", "ITEM_TEXT_TL_7", "ITEM_TEXT_TL_8", "ITEM_TEXT_TL_9", "NAME", "OBJECT_VERSION_NUMBER", "RATING_MODEL_ID", "STATE_PROVINCE_ID", "GOAL_CATEGORY", "GOAL_SUB_TYPE", "GOAL_BUSINESS_UNIT_NAME", "GOAL_DEPARTMENT_NAME", "GOAL_LEGAL_ENTITY_NAME", "GOAL_JOB_FAMILY_NAME", "CONTENT_TYPE_NAME", "CONTENT_TYPE_ID1", "BUSINESS_GROUP_ID1", "CONTENT_VALUE_SET_CODE", "CONTENT_VALUE_SET_ID1", "BUSINESS_GROUP_ID2") AS 
  SELECT ContentItemPEO.CONTENT_ITEM_ID, 
       ContentItemPEO.BUSINESS_GROUP_ID, 
       ContentItemPEO.CONTENT_ITEM_CODE, 
       ContentItemPEO.CONTENT_KEYFLEX_ID, 
       ContentItemPEO.CONTENT_SUPPLIER_CODE, 
       ContentItemPEO.CONTENT_TYPE_ID, 
       ContentItemPEO.CONTENT_VALUE_SET_ID, 
       ContentItemPEO.COUNTRY_ID, 
       ContentItemPEO.CREATED_BY, 
       ContentItemPEO.CREATION_DATE, 
       ContentItemPEO.DATE_FROM, 
       ContentItemPEO.DATE_TO, 
       ContentItemPEO.ITEM_DATE_1, 
       ContentItemPEO.ITEM_DATE_10, 
       ContentItemPEO.ITEM_DATE_2, 
       ContentItemPEO.ITEM_DATE_3, 
       ContentItemPEO.ITEM_DATE_4, 
       ContentItemPEO.ITEM_DATE_5, 
       ContentItemPEO.ITEM_DATE_6, 
       ContentItemPEO.ITEM_DATE_7, 
       ContentItemPEO.ITEM_DATE_8, 
       ContentItemPEO.ITEM_DATE_9, 
       ContentItemPEO.ITEM_DESCRIPTION, 
       ContentItemPEO.ITEM_DESCRLONG, 
       ContentItemPEO.ITEM_NUMBER_1, 
       ContentItemPEO.ITEM_NUMBER_10, 
       ContentItemPEO.ITEM_NUMBER_2, 
       ContentItemPEO.ITEM_NUMBER_3, 
       ContentItemPEO.ITEM_NUMBER_4, 
       ContentItemPEO.ITEM_NUMBER_5, 
       ContentItemPEO.ITEM_NUMBER_6, 
       ContentItemPEO.ITEM_NUMBER_7, 
       ContentItemPEO.ITEM_NUMBER_8, 
       ContentItemPEO.ITEM_NUMBER_9, 
       ContentItemPEO.ITEM_TEXT_1, 
       ContentItemPEO.ITEM_TEXT_10, 
       ContentItemPEO.ITEM_TEXT_11, 
       ContentItemPEO.ITEM_TEXT_12, 
       ContentItemPEO.ITEM_TEXT_13, 
       ContentItemPEO.ITEM_TEXT_14, 
       ContentItemPEO.ITEM_TEXT_15, 
       ContentItemPEO.ITEM_TEXT_16, 
       ContentItemPEO.ITEM_TEXT_17, 
       ContentItemPEO.ITEM_TEXT_18, 
       ContentItemPEO.ITEM_TEXT_19, 
       ContentItemPEO.ITEM_TEXT_2, 
       ContentItemPEO.ITEM_TEXT_20, 
       ContentItemPEO.ITEM_TEXT_21, 
       ContentItemPEO.ITEM_TEXT_22, 
       ContentItemPEO.ITEM_TEXT_23, 
       ContentItemPEO.ITEM_TEXT_24, 
       ContentItemPEO.ITEM_TEXT_25, 
       ContentItemPEO.ITEM_TEXT_26, 
       ContentItemPEO.ITEM_TEXT_27, 
       ContentItemPEO.ITEM_TEXT_28, 
       ContentItemPEO.ITEM_TEXT_29, 
       ContentItemPEO.ITEM_TEXT_3, 
       ContentItemPEO.ITEM_TEXT_30, 
       ContentItemPEO.ITEM_TEXT_4, 
       ContentItemPEO.ITEM_TEXT_5, 
       ContentItemPEO.ITEM_TEXT_6, 
       ContentItemPEO.ITEM_TEXT_7, 
       ContentItemPEO.ITEM_TEXT_8, 
       ContentItemPEO.ITEM_TEXT_9, 
       ContentItemPEO.ITEM_TEXT_TL_1, 
       ContentItemPEO.ITEM_TEXT_TL_10, 
       ContentItemPEO.ITEM_TEXT_TL_11, 
       ContentItemPEO.ITEM_TEXT_TL_12, 
       ContentItemPEO.ITEM_TEXT_TL_13, 
       ContentItemPEO.ITEM_TEXT_TL_14, 
       ContentItemPEO.ITEM_TEXT_TL_15, 
       ContentItemPEO.ITEM_TEXT_TL_2, 
       ContentItemPEO.ITEM_TEXT_TL_3, 
       ContentItemPEO.ITEM_TEXT_TL_4, 
       ContentItemPEO.ITEM_TEXT_TL_5, 
       ContentItemPEO.ITEM_TEXT_TL_6, 
       ContentItemPEO.ITEM_TEXT_TL_7, 
       ContentItemPEO.ITEM_TEXT_TL_8, 
       ContentItemPEO.ITEM_TEXT_TL_9, 
       ContentItemPEO.NAME, 
       ContentItemPEO.OBJECT_VERSION_NUMBER, 
       ContentItemPEO.RATING_MODEL_ID, 
       ContentItemPEO.STATE_PROVINCE_ID, 
       (SELECT meaning FROM fnd_lookup_values_tl WHERE ((ContentItemPEO.ITEM_TEXT_9 = 'PERFORMANCE' and lookup_type = 'HRG_PERF_GOAL_CATEGORY') OR (ContentItemPEO.ITEM_TEXT_9 = 'DEVELOPMENT' and lookup_type = 'HRG_DEV_GOAL_CATEGORY')) AND lookup_code = ContentItemPEO.ITEM_TEXT_8 AND language = userenv('LANG')) AS GOAL_CATEGORY, 
       (SELECT meaning FROM fnd_lookup_values_tl WHERE lookup_type = 'HRG_SUB_TYPE_CODE' AND lookup_code = ContentItemPEO.ITEM_TEXT_11 AND language = userenv('LANG')) AS GOAL_SUB_TYPE, 
       (SELECT name FROM  hr_organization_units_f_tl WHERE organization_id = ContentItemPEO.ITEM_NUMBER_1 AND (trunc(sysdate) BETWEEN effective_start_date AND effective_end_date) AND language = userenv('LANG') AND rownum = 1) AS GOAL_BUSINESS_UNIT_NAME, 
       (SELECT name FROM  hr_organization_units_f_tl WHERE organization_id = ContentItemPEO.ITEM_NUMBER_2 AND (trunc(sysdate) BETWEEN effective_start_date AND effective_end_date) AND language = userenv('LANG') AND rownum = 1) AS GOAL_DEPARTMENT_NAME, 
       (SELECT name FROM  hr_organization_units_f_tl WHERE organization_id = ContentItemPEO.ITEM_NUMBER_3 AND (trunc(sysdate) BETWEEN effective_start_date AND effective_end_date) AND language = userenv('LANG') AND rownum = 1) AS GOAL_LEGAL_ENTITY_NAME, 
       (SELECT job_family_name FROM per_job_family_f_tl WHERE job_family_id = ContentItemPEO.ITEM_NUMBER_5 AND (trunc(sysdate) BETWEEN effective_start_date AND effective_end_date) AND language = USERENV('LANG') AND rownum= 1) AS GOAL_JOB_FAMILY_NAME, 
       ContentTypePEO.CONTENT_TYPE_NAME, 
       ContentTypePEO.CONTENT_TYPE_ID AS CONTENT_TYPE_ID1, 
       ContentTypePEO.BUSINESS_GROUP_ID AS BUSINESS_GROUP_ID1, 
       ContentTypeValueSetPEO.CONTENT_VALUE_SET_CODE, 
       ContentTypeValueSetPEO.CONTENT_VALUE_SET_ID AS CONTENT_VALUE_SET_ID1, 
       ContentTypeValueSetPEO.BUSINESS_GROUP_ID AS BUSINESS_GROUP_ID2
FROM HRT_CONTENT_ITEMS_VL ContentItemPEO, HRT_CONTENT_TYPES_VL ContentTypePEO, HRT_CONTENT_TP_VALUESETS_VL ContentTypeValueSetPEO
WHERE TRUNC(SYSDATE) BETWEEN ContentItemPEO.DATE_FROM AND NVL(ContentItemPEO.DATE_TO,TO_DATE('4712-12-31','YYYY-MM-DD')) 
AND ContentItemPEO.CONTENT_TYPE_ID = ContentTypePEO.CONTENT_TYPE_ID(+)
AND ContentItemPEO.BUSINESS_GROUP_ID = ContentTypePEO.BUSINESS_GROUP_ID(+) 
AND ContentItemPEO.CONTENT_VALUE_SET_ID = ContentTypeValueSetPEO.CONTENT_VALUE_SET_ID(+) 
AND ContentItemPEO.BUSINESS_GROUP_ID = ContentTypeValueSetPEO.BUSINESS_GROUP_ID(+)
AND ContentItemPEO.BUSINESS_GROUP_ID = 202;